spring:
  batch:
    job:
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: always
      isolation-level-for-create: default
  datasource:
    url: jdbc:mariadb://localhost:3306/Batch_25_06?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ""
  jpa:
    show-sql: true