spring:
  batch:
    job:
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mariadb://localhost:3306/Batch_25_06?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ""
  jpa:
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:/org/springframework/batch/core/schema-mariadb.sql